"""Alembic environment.

Reads the database URL from ``SMARTMATCH_DATABASE_URL`` when present, so the
same migration set runs against a developer's local PostgreSQL, CI's service
container, and a deployed environment without editing a checked-in file.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_url = os.getenv("SMARTMATCH_DATABASE_URL")
if _url:
    config.set_main_option("sqlalchemy.url", _url)

# Migrations are hand-written rather than autogenerated from ORM models. The
# composite tenant-safe keys in v1.1 §2.2 are the point of the schema, and
# autogenerate does not reliably reproduce them — a silently simplified foreign
# key would remove the isolation guarantee without anyone noticing.
target_metadata = None


def run_migrations_offline() -> None:
    """Emit SQL without a live connection, for review."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
