import { useQuery } from "@tanstack/react-query";
import { CalendarDays, MapPin } from "lucide-react";
import { usePrincipalKey } from "../../components/PrincipalQueryProvider";
import { useAuthorizedUnitId } from "../../hooks/useAuthorizedUnit";
import { fetchMySpeakerEngagements, type SpeakerEventStatus } from "../../../lib/api";

const labels: Record<SpeakerEventStatus, string> = { not_emailed_yet: "Not Emailed Yet", awaiting_response: "Awaiting Response", declined: "Declined", ready_for_handoff: "Ready for Handoff", handed_off: "Handed Off", awaiting_final_confirmation: "Awaiting Final Confirmation", confirmed: "Confirmed", withdrawn: "Withdrawn", attended: "Attended", did_not_attend: "Did Not Attend", event_cancelled: "Event Cancelled" };

export function VolunteerAssignments() {
  const unitId = useAuthorizedUnitId("volunteer"); const principalKey = usePrincipalKey();
  const query = useQuery({ queryKey: [principalKey, "speaker-portal", unitId, "engagements"], queryFn: () => fetchMySpeakerEngagements(unitId!), enabled: Boolean(principalKey && unitId) });
  return <div className="space-y-6"><header><h1 className="text-3xl font-semibold">Engagements</h1><p className="mt-2 text-muted-foreground">Events that have been handed to you for confirmation or attendance.</p></header>{query.isLoading ? <div className="h-32 animate-pulse rounded-2xl bg-muted" /> : null}{query.error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-destructive">{query.error instanceof Error ? query.error.message : "Your engagements could not be loaded."}</p> : null}<div className="grid gap-4 lg:grid-cols-2">{(query.data ?? []).map((item) => <article key={item.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold">{item.event_title}</h2><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{labels[item.status]}</span></div><p className="mt-4 flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="h-4 w-4" />{item.starts_at ? new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeStyle: "short", timeZone: item.time_zone ?? undefined }).format(new Date(item.starts_at)) : item.on_date ? `${item.on_date} · All day` : "Schedule not set"}</p><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4" />{item.location ?? "Location not provided"}</p></article>)}</div>{!query.isLoading && !query.error && !query.data?.length ? <div className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">No engagements have been handed to you yet.</div> : null}</div>;
}
