import type {
  CalendarAssignmentSummary,
  CalendarEventSummary,
  CppEvent,
  FeedbackStatsSummary,
  PipelineRecord,
  QrStatsSummary,
  RankedMatch,
  Specialist,
} from "./api";

export const MOCK_SPECIALISTS: Specialist[] = [
  {
    name: "Dr. Sarah Chen",
    board_role: "President",
    metro_region: "Los Angeles - West",
    company: "TechBridge AI",
    title: "VP Data Science",
    expertise_tags: "AI, machine learning, hackathons",
    initials: "SC",
  },
  {
    name: "Marcus Webb",
    board_role: "VP Programs",
    metro_region: "Los Angeles - Central",
    company: "Webb Consulting Group",
    title: "Principal Engineer",
    expertise_tags: "cloud infrastructure, DevOps, mentoring",
    initials: "MW",
  },
  {
    name: "Priya Nair",
    board_role: "Secretary",
    metro_region: "Inland Empire",
    company: "Nair Analytics",
    title: "Data Science Lead",
    expertise_tags: "data engineering, Python, analytics",
    initials: "PN",
  },
  {
    name: "James Rodriguez",
    board_role: "Treasurer",
    metro_region: "Los Angeles - East",
    company: "Fintech Horizons",
    title: "Head of Finance Technology",
    expertise_tags: "fintech, blockchain, product management",
    initials: "JR",
  },
  {
    name: "Dr. Emily Park",
    board_role: "Director",
    metro_region: "Orange County",
    company: "ParkHealth AI",
    title: "Chief AI Officer",
    expertise_tags: "healthcare AI, NLP, clinical informatics",
    initials: "EP",
  },
  {
    name: "Kevin O'Brien",
    board_role: "Director",
    metro_region: "San Gabriel Valley",
    company: "O'Brien Tech Ventures",
    title: "CTO",
    expertise_tags: "startup mentorship, venture capital, mobile",
    initials: "KO",
  },
  {
    name: "Aisha Johnson",
    board_role: "Director",
    metro_region: "Los Angeles - South",
    company: "Johnson DEI Consulting",
    title: "Director of Diversity Programs",
    expertise_tags: "DEI, workforce development, education",
    initials: "AJ",
  },
  {
    name: "Dr. Michael Torres",
    board_role: "Director",
    metro_region: "Los Angeles - West",
    company: "Torres Robotics Lab",
    title: "Research Scientist",
    expertise_tags: "robotics, computer vision, embedded systems",
    initials: "MT",
  },
  {
    name: "Lisa Chang",
    board_role: "Director",
    metro_region: "San Fernando Valley",
    company: "Chang Media Tech",
    title: "VP Product",
    expertise_tags: "UX design, product strategy, user research",
    initials: "LC",
  },
  {
    name: "Robert Kim",
    board_role: "Director",
    metro_region: "Long Beach",
    company: "Kim Cyber Security",
    title: "CISO",
    expertise_tags: "cybersecurity, network security, compliance",
    initials: "RK",
  },
];

export const MOCK_PIPELINE: PipelineRecord[] = [
  // Matched stage (6 records)
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Dr. Emily Park", match_score: "0.91", rank: "1", stage: "Matched", stage_order: "1" },
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Kevin O'Brien", match_score: "0.78", rank: "2", stage: "Matched", stage_order: "1" },
  { event_name: "ITC Conference", speaker_name: "Lisa Chang", match_score: "0.85", rank: "1", stage: "Matched", stage_order: "1" },
  { event_name: "Bronco Startup Challenge", speaker_name: "Robert Kim", match_score: "0.72", rank: "1", stage: "Matched", stage_order: "1" },
  { event_name: "IA West Annual Summit", speaker_name: "Aisha Johnson", match_score: "0.80", rank: "1", stage: "Matched", stage_order: "1" },
  { event_name: "Tech Career Fair", speaker_name: "Dr. Michael Torres", match_score: "0.77", rank: "1", stage: "Matched", stage_order: "1" },
  // Contacted stage (5 records)
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Dr. Sarah Chen", match_score: "0.89", rank: "1", stage: "Contacted", stage_order: "2" },
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Priya Nair", match_score: "0.83", rank: "3", stage: "Contacted", stage_order: "2" },
  { event_name: "ITC Conference", speaker_name: "James Rodriguez", match_score: "0.76", rank: "2", stage: "Contacted", stage_order: "2" },
  { event_name: "Bronco Startup Challenge", speaker_name: "Dr. Emily Park", match_score: "0.88", rank: "1", stage: "Contacted", stage_order: "2" },
  { event_name: "IA West Annual Summit", speaker_name: "Marcus Webb", match_score: "0.74", rank: "2", stage: "Contacted", stage_order: "2" },
  // Confirmed stage (4 records)
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Marcus Webb", match_score: "0.82", rank: "2", stage: "Confirmed", stage_order: "3" },
  { event_name: "ITC Conference", speaker_name: "Dr. Sarah Chen", match_score: "0.90", rank: "1", stage: "Confirmed", stage_order: "3" },
  { event_name: "IA West Annual Summit", speaker_name: "Kevin O'Brien", match_score: "0.79", rank: "1", stage: "Confirmed", stage_order: "3" },
  { event_name: "Tech Career Fair", speaker_name: "Priya Nair", match_score: "0.81", rank: "1", stage: "Confirmed", stage_order: "3" },
  // Attended stage (3 records)
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Dr. Sarah Chen", match_score: "0.89", rank: "1", stage: "Attended", stage_order: "4" },
  { event_name: "ITC Conference", speaker_name: "Aisha Johnson", match_score: "0.75", rank: "2", stage: "Attended", stage_order: "4" },
  { event_name: "Bronco Startup Challenge", speaker_name: "Marcus Webb", match_score: "0.82", rank: "1", stage: "Attended", stage_order: "4" },
  // Member Inquiry stage (2 records)
  { event_name: "AI for a Better Future Hackathon", speaker_name: "Marcus Webb", match_score: "0.82", rank: "1", stage: "Member Inquiry", stage_order: "5" },
  { event_name: "ITC Conference", speaker_name: "Dr. Sarah Chen", match_score: "0.89", rank: "1", stage: "Member Inquiry", stage_order: "5" },
];

export const MOCK_EVENTS: CppEvent[] = [
  { "Event / Program": "AI for a Better Future Hackathon", Category: "Innovation", "Recurrence (typical)": "Annual", "Host / Unit": "Cal Poly Pomona", "Volunteer Roles (fit)": "Mentor, Judge", "Primary Audience": "Students" },
  { "Event / Program": "ITC Conference", Category: "Technology", "Recurrence (typical)": "Annual", "Host / Unit": "UC Irvine", "Volunteer Roles (fit)": "Speaker, Panelist", "Primary Audience": "Professionals" },
  { "Event / Program": "Bronco Startup Challenge", Category: "Entrepreneurship", "Recurrence (typical)": "Annual", "Host / Unit": "Cal Poly Pomona", "Volunteer Roles (fit)": "Judge, Mentor", "Primary Audience": "Students" },
  { "Event / Program": "IA West Annual Summit", Category: "Networking", "Recurrence (typical)": "Annual", "Host / Unit": "IA West Chapter", "Volunteer Roles (fit)": "Speaker, Facilitator", "Primary Audience": "Members" },
  { "Event / Program": "Tech Career Fair", Category: "Career Development", "Recurrence (typical)": "Semi-Annual", "Host / Unit": "CSU Fullerton", "Volunteer Roles (fit)": "Recruiter, Speaker", "Primary Audience": "Students" },
];

export const MOCK_CALENDAR_EVENTS: CalendarEventSummary[] = [
  {
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    event_date: "2026-04-15",
    region: "Los Angeles - West",
    nearby_universities: ["Cal Poly Pomona", "UCLA"],
    suggested_lecture_window: "Week of April 8–12",
    coverage_status: "covered",
    coverage_label: "IA covered",
    coverage_ratio: 1.0,
    assigned_volunteers: ["Dr. Sarah Chen", "Marcus Webb"],
    assignment_count: 2,
    open_slots: 0,
    status_color: "#005394",
  },
  {
    event_id: "evt-002",
    event_name: "ITC Conference",
    event_date: "2026-05-10",
    region: "Orange County",
    nearby_universities: ["UC Irvine", "Cal State Fullerton"],
    suggested_lecture_window: "Week of May 4–8",
    coverage_status: "partial",
    coverage_label: "Partial coverage",
    coverage_ratio: 0.5,
    assigned_volunteers: ["Priya Nair"],
    assignment_count: 1,
    open_slots: 1,
    status_color: "#c47c00",
  },
  {
    event_id: "evt-003",
    event_name: "Bronco Startup Challenge",
    event_date: "2026-06-05",
    region: "Inland Empire",
    nearby_universities: ["Cal Poly Pomona", "UC Riverside"],
    suggested_lecture_window: "Week of May 29 – June 2",
    coverage_status: "needs_coverage",
    coverage_label: "Needs volunteers",
    coverage_ratio: 0.0,
    assigned_volunteers: [],
    assignment_count: 0,
    open_slots: 2,
    status_color: "#d14343",
  },
  {
    event_id: "evt-004",
    event_name: "IA West Annual Summit",
    event_date: "2026-07-20",
    region: "Los Angeles - Central",
    nearby_universities: ["USC", "Cal State LA"],
    suggested_lecture_window: "Week of July 14–18",
    coverage_status: "covered",
    coverage_label: "IA covered",
    coverage_ratio: 1.0,
    assigned_volunteers: ["Kevin O'Brien", "Aisha Johnson"],
    assignment_count: 2,
    open_slots: 0,
    status_color: "#005394",
  },
  {
    event_id: "evt-005",
    event_name: "Tech Career Fair",
    event_date: "2026-08-15",
    region: "San Gabriel Valley",
    nearby_universities: ["Cal State Fullerton", "Cal Poly Pomona"],
    suggested_lecture_window: "Week of Aug 10–14",
    coverage_status: "partial",
    coverage_label: "Partial coverage",
    coverage_ratio: 0.5,
    assigned_volunteers: ["Lisa Chang"],
    assignment_count: 1,
    open_slots: 1,
    status_color: "#c47c00",
  },
];

export const MOCK_CALENDAR_ASSIGNMENTS: CalendarAssignmentSummary[] = [
  {
    assignment_id: "asgn-001",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    event_date: "2026-04-15",
    region: "Los Angeles - West",
    volunteer_name: "Dr. Sarah Chen",
    volunteer_title: "VP Data Science",
    volunteer_company: "TechBridge AI",
    stage: "Confirmed",
    coverage_status: "covered",
    coverage_label: "IA covered",
    volunteer_fatigue: 0.35,
    recovery_status: "Available",
    recovery_label: "Available",
    recent_assignment_count: 1,
    days_since_last_assignment: 45,
    travel_burden: 0.2,
    event_cadence: 2,
    status_color: "#0f766e",
  },
  {
    assignment_id: "asgn-002",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    event_date: "2026-04-15",
    region: "Los Angeles - West",
    volunteer_name: "Marcus Webb",
    volunteer_title: "Principal Engineer",
    volunteer_company: "Webb Consulting Group",
    stage: "Confirmed",
    coverage_status: "covered",
    coverage_label: "IA covered",
    volunteer_fatigue: 0.55,
    recovery_status: "Needs Rest",
    recovery_label: "Needs Rest",
    recent_assignment_count: 3,
    days_since_last_assignment: 12,
    travel_burden: 0.4,
    event_cadence: 4,
    status_color: "#c47c00",
  },
  {
    assignment_id: "asgn-003",
    event_id: "evt-002",
    event_name: "ITC Conference",
    event_date: "2026-05-10",
    region: "Orange County",
    volunteer_name: "Priya Nair",
    volunteer_title: "Data Science Lead",
    volunteer_company: "Nair Analytics",
    stage: "Matched",
    coverage_status: "partial",
    coverage_label: "Partial coverage",
    volunteer_fatigue: 0.2,
    recovery_status: "Available",
    recovery_label: "Available",
    recent_assignment_count: 1,
    days_since_last_assignment: 90,
    travel_burden: 0.3,
    event_cadence: 1,
    status_color: "#0f766e",
  },
];

export const MOCK_QR_STATS: QrStatsSummary = {
  total_generated: 5,
  total_scans: 42,
  total_conversions: 12,
  conversion_rate: 0.286,
  entries: [
    {
      referral_code: "sarah-chen-hackathon",
      speaker_name: "Dr. Sarah Chen",
      speaker_title: "VP Data Science",
      speaker_company: "TechBridge AI",
      event_name: "AI for a Better Future Hackathon",
      generated_at: "2026-03-01T10:00:00Z",
      destination_url: "",
      scan_url: "",
      scan_count: 18,
      conversion_count: 6,
      conversion_rate: 0.333,
      last_scanned_at: "2026-03-25T14:30:00Z",
      qr_svg: "",
      qr_svg_data_url: "",
      qr_png_data_url: "",
      qr_image_url: "",
      download_url: "",
    },
    {
      referral_code: "marcus-webb-hackathon",
      speaker_name: "Marcus Webb",
      speaker_title: "Principal Engineer",
      speaker_company: "Webb Consulting Group",
      event_name: "AI for a Better Future Hackathon",
      generated_at: "2026-03-01T11:00:00Z",
      destination_url: "",
      scan_url: "",
      scan_count: 10,
      conversion_count: 3,
      conversion_rate: 0.3,
      last_scanned_at: "2026-03-22T09:00:00Z",
      qr_svg: "",
      qr_svg_data_url: "",
      qr_png_data_url: "",
      qr_image_url: "",
      download_url: "",
    },
    {
      referral_code: "priya-nair-itc",
      speaker_name: "Priya Nair",
      speaker_title: "Data Science Lead",
      speaker_company: "Nair Analytics",
      event_name: "ITC Conference",
      generated_at: "2026-03-05T09:30:00Z",
      destination_url: "",
      scan_url: "",
      scan_count: 8,
      conversion_count: 2,
      conversion_rate: 0.25,
      last_scanned_at: "2026-03-20T16:00:00Z",
      qr_svg: "",
      qr_svg_data_url: "",
      qr_png_data_url: "",
      qr_image_url: "",
      download_url: "",
    },
    {
      referral_code: "kevin-obrien-summit",
      speaker_name: "Kevin O'Brien",
      speaker_title: "CTO",
      speaker_company: "O'Brien Tech Ventures",
      event_name: "IA West Annual Summit",
      generated_at: "2026-03-10T08:00:00Z",
      destination_url: "",
      scan_url: "",
      scan_count: 4,
      conversion_count: 1,
      conversion_rate: 0.25,
      last_scanned_at: "2026-03-18T11:00:00Z",
      qr_svg: "",
      qr_svg_data_url: "",
      qr_png_data_url: "",
      qr_image_url: "",
      download_url: "",
    },
    {
      referral_code: "aisha-johnson-summit",
      speaker_name: "Aisha Johnson",
      speaker_title: "Director of Diversity Programs",
      speaker_company: "Johnson DEI Consulting",
      event_name: "IA West Annual Summit",
      generated_at: "2026-03-10T09:00:00Z",
      destination_url: "",
      scan_url: "",
      scan_count: 2,
      conversion_count: 0,
      conversion_rate: 0,
      last_scanned_at: "",
      qr_svg: "",
      qr_svg_data_url: "",
      qr_png_data_url: "",
      qr_image_url: "",
      download_url: "",
    },
  ],
};

export const MOCK_FEEDBACK_STATS: FeedbackStatsSummary = {
  total_feedback: 8,
  accepted: 5,
  declined: 3,
  acceptance_rate: 0.625,
  attended_count: 3,
  membership_interest_count: 2,
  membership_interest_rate: 0.4,
  average_coordinator_rating: 4.2,
  average_match_score_accepted: 0.84,
  average_match_score_declined: 0.61,
  pain_score: 2.1,
  decline_reasons: [
    { reason: "Schedule conflict", count: 2 },
    { reason: "Topic mismatch", count: 1 },
  ],
  event_outcomes: [
    { outcome: "Attended", count: 3 },
    { outcome: "Membership Interest", count: 2 },
    { outcome: "No Show", count: 0 },
  ],
  trend: [
    { date: "2026-01-15", feedback_count: 2, accepted: 1, declined: 1, acceptance_rate: 0.5 },
    { date: "2026-02-20", feedback_count: 3, accepted: 2, declined: 1, acceptance_rate: 0.667 },
    { date: "2026-03-10", feedback_count: 3, accepted: 2, declined: 1, acceptance_rate: 0.667 },
  ],
  default_weights: {
    topic_relevance: 0.3,
    role_fit: 0.2,
    geographic_proximity: 0.15,
    calendar_fit: 0.15,
    historical_conversion: 0.1,
    student_interest: 0.05,
    volunteer_fatigue: 0.05,
  },
  current_weights: {
    topic_relevance: 0.32,
    role_fit: 0.22,
    geographic_proximity: 0.14,
    calendar_fit: 0.14,
    historical_conversion: 0.1,
    student_interest: 0.04,
    volunteer_fatigue: 0.04,
  },
  suggested_weights: {
    topic_relevance: 0.33,
    role_fit: 0.22,
    geographic_proximity: 0.14,
    calendar_fit: 0.13,
    historical_conversion: 0.1,
    student_interest: 0.04,
    volunteer_fatigue: 0.04,
  },
  recommended_adjustments: [
    {
      factor: "topic_relevance",
      from_weight: 0.3,
      to_weight: 0.33,
      delta: 0.03,
      rationale: "Accepted matches consistently score higher on topic relevance",
    },
  ],
  weight_history: [
    {
      timestamp: "2026-02-20T12:00:00Z",
      total_feedback: 5,
      accepted: 3,
      declined: 2,
      acceptance_rate: 0.6,
      pain_score: 2.8,
      weights: {
        topic_relevance: 0.3,
        role_fit: 0.2,
        geographic_proximity: 0.15,
        calendar_fit: 0.15,
        historical_conversion: 0.1,
        student_interest: 0.05,
        volunteer_fatigue: 0.05,
      },
      baseline_weights: {
        topic_relevance: 0.3,
        role_fit: 0.2,
        geographic_proximity: 0.15,
        calendar_fit: 0.15,
        historical_conversion: 0.1,
        student_interest: 0.05,
        volunteer_fatigue: 0.05,
      },
      adjustments: [],
    },
    {
      timestamp: "2026-03-10T15:00:00Z",
      total_feedback: 8,
      accepted: 5,
      declined: 3,
      acceptance_rate: 0.625,
      pain_score: 2.1,
      weights: {
        topic_relevance: 0.32,
        role_fit: 0.22,
        geographic_proximity: 0.14,
        calendar_fit: 0.14,
        historical_conversion: 0.1,
        student_interest: 0.04,
        volunteer_fatigue: 0.04,
      },
      baseline_weights: {
        topic_relevance: 0.3,
        role_fit: 0.2,
        geographic_proximity: 0.15,
        calendar_fit: 0.15,
        historical_conversion: 0.1,
        student_interest: 0.05,
        volunteer_fatigue: 0.05,
      },
      adjustments: [
        {
          factor: "topic_relevance",
          from_weight: 0.3,
          to_weight: 0.32,
          delta: 0.02,
          rationale: "Higher acceptance on topic-matched specialists",
        },
      ],
    },
  ],
};

export const MOCK_RANKED_MATCHES: RankedMatch[] = [
  {
    rank: 1,
    name: "Dr. Sarah Chen",
    title: "VP Data Science",
    company: "TechBridge AI",
    board_role: "President",
    metro_region: "Los Angeles - West",
    expertise_tags: "AI, machine learning, hackathons",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    score: 0.89,
    match_score: 0.89,
    total_score: 0.89,
    volunteer_fatigue: 0.35,
    recovery_status: "Available",
    recovery_label: "Available",
    factor_scores: {
      topic_relevance: 0.95,
      role_fit: 0.88,
      geographic_proximity: 0.9,
      calendar_fit: 0.85,
      historical_conversion: 0.82,
      student_interest: 0.9,
      volunteer_fatigue: 0.65,
    },
    weighted_factor_scores: {
      topic_relevance: 0.304,
      role_fit: 0.194,
      geographic_proximity: 0.126,
      calendar_fit: 0.119,
      historical_conversion: 0.082,
      student_interest: 0.036,
      volunteer_fatigue: 0.026,
    },
  },
  {
    rank: 2,
    name: "Marcus Webb",
    title: "Principal Engineer",
    company: "Webb Consulting Group",
    board_role: "VP Programs",
    metro_region: "Los Angeles - Central",
    expertise_tags: "cloud infrastructure, DevOps, mentoring",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    score: 0.82,
    match_score: 0.82,
    total_score: 0.82,
    volunteer_fatigue: 0.55,
    recovery_status: "Needs Rest",
    recovery_label: "Needs Rest",
    factor_scores: {
      topic_relevance: 0.80,
      role_fit: 0.85,
      geographic_proximity: 0.88,
      calendar_fit: 0.78,
      historical_conversion: 0.75,
      student_interest: 0.80,
      volunteer_fatigue: 0.45,
    },
    weighted_factor_scores: {
      topic_relevance: 0.256,
      role_fit: 0.187,
      geographic_proximity: 0.123,
      calendar_fit: 0.109,
      historical_conversion: 0.075,
      student_interest: 0.032,
      volunteer_fatigue: 0.018,
    },
  },
  {
    rank: 3,
    name: "Priya Nair",
    title: "Data Science Lead",
    company: "Nair Analytics",
    board_role: "Secretary",
    metro_region: "Inland Empire",
    expertise_tags: "data engineering, Python, analytics",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    score: 0.77,
    match_score: 0.77,
    total_score: 0.77,
    volunteer_fatigue: 0.2,
    recovery_status: "Available",
    recovery_label: "Available",
    factor_scores: {
      topic_relevance: 0.82,
      role_fit: 0.78,
      geographic_proximity: 0.72,
      calendar_fit: 0.80,
      historical_conversion: 0.68,
      student_interest: 0.75,
      volunteer_fatigue: 0.8,
    },
    weighted_factor_scores: {
      topic_relevance: 0.262,
      role_fit: 0.172,
      geographic_proximity: 0.101,
      calendar_fit: 0.112,
      historical_conversion: 0.068,
      student_interest: 0.03,
      volunteer_fatigue: 0.032,
    },
  },
  {
    rank: 4,
    name: "Dr. Emily Park",
    title: "Chief AI Officer",
    company: "ParkHealth AI",
    board_role: "Director",
    metro_region: "Orange County",
    expertise_tags: "healthcare AI, NLP, clinical informatics",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    score: 0.74,
    match_score: 0.74,
    total_score: 0.74,
    volunteer_fatigue: 0.15,
    recovery_status: "Available",
    recovery_label: "Available",
    factor_scores: {
      topic_relevance: 0.85,
      role_fit: 0.75,
      geographic_proximity: 0.65,
      calendar_fit: 0.78,
      historical_conversion: 0.60,
      student_interest: 0.72,
      volunteer_fatigue: 0.85,
    },
    weighted_factor_scores: {
      topic_relevance: 0.272,
      role_fit: 0.165,
      geographic_proximity: 0.091,
      calendar_fit: 0.109,
      historical_conversion: 0.06,
      student_interest: 0.029,
      volunteer_fatigue: 0.034,
    },
  },
  {
    rank: 5,
    name: "Dr. Michael Torres",
    title: "Research Scientist",
    company: "Torres Robotics Lab",
    board_role: "Director",
    metro_region: "Los Angeles - West",
    expertise_tags: "robotics, computer vision, embedded systems",
    event_id: "evt-001",
    event_name: "AI for a Better Future Hackathon",
    score: 0.69,
    match_score: 0.69,
    total_score: 0.69,
    volunteer_fatigue: 0.1,
    recovery_status: "Available",
    recovery_label: "Available",
    factor_scores: {
      topic_relevance: 0.75,
      role_fit: 0.70,
      geographic_proximity: 0.82,
      calendar_fit: 0.65,
      historical_conversion: 0.55,
      student_interest: 0.68,
      volunteer_fatigue: 0.9,
    },
    weighted_factor_scores: {
      topic_relevance: 0.24,
      role_fit: 0.154,
      geographic_proximity: 0.115,
      calendar_fit: 0.091,
      historical_conversion: 0.055,
      student_interest: 0.027,
      volunteer_fatigue: 0.036,
    },
  },
];
