/**
 * Frontend query cache (plan P4, lane F1).
 *
 * This module is deliberately framework-light: no `import.meta.env`, no
 * `@/`-alias imports, and no React import. It must be importable from a
 * plain Node.js test run (`node --test tests/`) as well as from Vite, so it
 * can be exercised directly against a real `QueryClient` in
 * `tests/queryClient.principal-isolation.test.ts` without a bundler or a
 * DOM. Anything Vite-only or React-only belongs in
 * `src/lib/principalKey.ts` or `src/app/components/PrincipalQueryProvider.tsx`
 * instead.
 *
 * --- THE HARD SAFETY RULE --------------------------------------------------
 *
 * A cache must NEVER serve one principal's data to another. Two mechanisms
 * enforce that here, and BOTH are required -- neither is sufficient alone:
 *
 * 1. Key scoping: every cache key generated by {@link metricsQueryKey} and
 *    {@link drilldownQueryKey} carries the principal as its FIRST segment.
 *    This means two different principals can never collide on the same
 *    cache entry, even if the cache were never cleared.
 *
 * 2. Mandatory clearing on identity change: key scoping alone still leaves
 *    stale-while-revalidate data sitting in the cache under an OLD
 *    principal's keys after that principal is no longer active. If a
 *    caller ever mis-derives a key (a bug in principal-key derivation, a
 *    future key-shape change that under-scopes, or simply forgetting to
 *    plumb the current principal through), scoping alone does nothing to
 *    protect against it, and old data can sit around indefinitely.
 *    Unconditionally clearing the entire cache on every OBSERVED identity
 *    change removes that risk at the source: after
 *    {@link PrincipalIdentityTracker.apply}'s `client.clear()` runs, there
 *    is nothing left in the cache to serve until the new principal's own
 *    fetches populate it. This is why `apply` calls `client.clear()` on ANY
 *    key change (including `X -> null` and `null -> X`), not just when
 *    moving between two known, non-null keys.
 */
import { QueryClient } from "@tanstack/react-query";

/** First segment of every principal-scoped query key. */
export type PrincipalKey = string;

/** Cache key for `GET /v1/units/{unit_id}/metrics`, scoped to a principal. */
export function metricsQueryKey(
  principalKey: PrincipalKey,
  unitId: string,
): readonly [PrincipalKey, "metrics", string] {
  return [principalKey, "metrics", unitId] as const;
}

/**
 * Cache key for `GET /v1/units/{unit_id}/metrics/{metric_name}/drill-down`,
 * scoped to a principal.
 */
export function drilldownQueryKey(
  principalKey: PrincipalKey,
  unitId: string,
  metricName: string,
): readonly [PrincipalKey, "drilldown", string, string] {
  return [principalKey, "drilldown", unitId, metricName] as const;
}

/**
 * Builds the app's shared {@link QueryClient}.
 *
 * - `staleTime: 30_000` -- ADR-0011 forbids presenting a stale value as
 *   live. 30s is short enough that a value is never shown meaningfully out
 *   of date, while still giving R4 (repeat navigation renders instantly via
 *   stale-while-revalidate) something to serve without a refetch-blocking
 *   spinner on every route change.
 * - `refetchOnWindowFocus: false` -- demo stability. A metrics panel must
 *   not silently re-fetch (and briefly show a loading state) just because
 *   the browser tab regained focus during a live walkthrough.
 * - `retry` -- see {@link shouldRetryQuery}. Retry ONLY applies to thrown
 *   errors (network failures, non-2xx responses surfaced as
 *   `ApiRequestError`). Per ADR-0011, a metric with `value: null` and an
 *   `unknown_reason` is a *successful* HTTP response, not a thrown error --
 *   `fetchUnitMetrics` resolves normally for it. React Query's retry logic
 *   only ever fires for a query function that *throws*, so an "unknown"
 *   metric is never retried, never transformed, and never treated as a cache
 *   miss: it is cached and served exactly like a known value.
 */
export function createAppQueryClient(): QueryClient {
  return new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: 30_000,
        refetchOnWindowFocus: false,
        retry: shouldRetryQuery,
      },
    },
  });
}

/** Maximum retry attempts for an error that is plausibly transient. */
const MAX_TRANSIENT_RETRIES = 2;

/**
 * Decides whether a thrown query error is worth retrying.
 *
 * A 4xx is the server's considered answer, not a blip: `401`/`403` mean this
 * principal may not read this resource and `404` means it is not there.
 * Repeating such a request cannot change the answer, so it is refused
 * outright rather than retried. That matters beyond politeness here: the
 * metrics-authorization decision (plan P1) is an unratified draft, so these
 * routes may or may not become gated. If they are gated, a retrying client
 * would turn every denied page load into a burst of denied requests -- and
 * this hook must behave correctly under either outcome without assuming one.
 *
 * Everything else -- a network failure, a 5xx, an error with no status at
 * all -- gets {@link MAX_TRANSIENT_RETRIES} further attempts.
 *
 * The status is read structurally rather than by importing `ApiRequestError`
 * from `src/lib/api.ts`: this module must stay importable from a plain Node
 * test run, and `api.ts` is Vite-only. `ApiRequestError` carries a numeric
 * `status`, which is all this needs.
 */
export function shouldRetryQuery(failureCount: number, error: unknown): boolean {
  const status = (error as { status?: unknown } | null)?.status;
  if (typeof status === "number" && status >= 400 && status < 500) {
    return false;
  }
  return failureCount < MAX_TRANSIENT_RETRIES;
}

/**
 * Tracks "the principal currently in effect" and enforces the
 * clear-on-change half of the hard safety rule above.
 *
 * Deliberately a plain class with explicit, resettable state (rather than
 * module-level mutable state) so tests can construct a fresh tracker per
 * test case with no cross-test leakage, and so the identity seam can be
 * exercised directly against a real `QueryClient` with no React and no DOM.
 */
export class PrincipalIdentityTracker {
  private currentKey: PrincipalKey | null = null;

  /** The principal key currently in effect, or `null` if none is known yet. */
  get current(): PrincipalKey | null {
    return this.currentKey;
  }

  /**
   * Applies a newly observed principal key.
   *
   * Call this on EVERY identity-relevant event, not just sign-out:
   *  - a bearer token is set, replaced, or cleared,
   *  - `fetchMe()` returns a different `user_id` than the one currently in
   *    effect,
   *  - `fetchMe()` fails (pass `null` to represent "no known principal").
   *
   * When `nextPrincipalKey` differs from {@link current} -- including a
   * change to or from `null` -- the entire query cache is cleared via
   * `client.clear()` before the new key is recorded. When it is unchanged,
   * this is a deliberate no-op: clearing on every call would destroy the
   * very caching this lane exists to add.
   */
  apply(client: QueryClient, nextPrincipalKey: PrincipalKey | null): void {
    if (nextPrincipalKey === this.currentKey) {
      return;
    }
    client.clear();
    this.currentKey = nextPrincipalKey;
  }

  /** Resets tracked state to "no principal known yet". Test-only helper. */
  reset(): void {
    this.currentKey = null;
  }
}

/** Creates a fresh, independent {@link PrincipalIdentityTracker}. */
export function createPrincipalIdentity(): PrincipalIdentityTracker {
  return new PrincipalIdentityTracker();
}
