import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router";
import { CalendarDays, ClipboardList, Sparkles } from "lucide-react";
import { usePrincipalKey } from "../../components/PrincipalQueryProvider";
import { fetchManualEvents, fetchSpeakerEvents, fetchUnitSpeakerFeedbackSummary } from "../../../lib/api";
import { useAuthorizedUnitId } from "../../hooks/useAuthorizedUnit";

export function CoordinatorHome() {
  const unitId = useAuthorizedUnitId("coordinator"); const principalKey = usePrincipalKey();
  const events = useQuery({ queryKey: [principalKey, "manual-events", unitId, "published"], queryFn: () => fetchManualEvents(unitId!, "published"), enabled: Boolean(principalKey && unitId) });
  const handoffs = useQuery({ queryKey: [principalKey, "speaker-events", unitId], queryFn: () => fetchSpeakerEvents(unitId!), enabled: Boolean(principalKey && unitId) });
  const feedback = useQuery({ queryKey: [principalKey, "unit-speaker-feedback", unitId], queryFn: () => fetchUnitSpeakerFeedbackSummary(unitId!), enabled: Boolean(principalKey && unitId) });
  if (!unitId) return <section className="rounded-2xl border bg-card p-8"><h1 className="text-3xl">Event Host</h1><p className="mt-2 text-muted-foreground">Sign in with an authorized unit to open your workspace.</p></section>;
  const ready = (handoffs.data ?? []).filter((record) => ["handed_off", "awaiting_final_confirmation", "confirmed"].includes(record.status));
  const summary = feedback.data;
  return <div className="space-y-6"><header><h1 className="text-3xl font-semibold">Event Host</h1><p className="mt-2 text-muted-foreground">Match published speakers to events and complete handoffs.</p></header><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border bg-card p-6 shadow-sm"><CalendarDays className="h-6 w-6 text-primary" /><p className="mt-4 text-3xl font-semibold">{events.isLoading ? "Loading" : events.data?.total ?? "Not available"}</p><p className="text-sm text-muted-foreground">Published events</p></article><article className="rounded-2xl border bg-card p-6 shadow-sm"><ClipboardList className="h-6 w-6 text-primary" /><p className="mt-4 text-3xl font-semibold">{handoffs.isLoading ? "Loading" : ready.length}</p><p className="text-sm text-muted-foreground">Handoffs needing host attention</p></article></div>{events.error || handoffs.error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-destructive">Workspace data could not be loaded.</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Link to="/coordinator-portal/events" className="rounded-2xl border bg-card p-6 shadow-sm hover:border-primary"><Sparkles className="h-6 w-6 text-primary" /><h2 className="mt-3 text-xl">Run Smart Match</h2><p className="mt-1 text-sm text-muted-foreground">Open an event to find up to three relevant speakers.</p></Link><Link to="/coordinator-portal/outreach" className="rounded-2xl border bg-card p-6 shadow-sm hover:border-primary"><ClipboardList className="h-6 w-6 text-primary" /><h2 className="mt-3 text-xl">Speaker handoffs</h2><p className="mt-1 text-sm text-muted-foreground">Request confirmation and record attendance.</p></Link></div><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl">Student feedback</h2><p className="mt-1 text-sm text-muted-foreground">Student feedback does not feed matching.</p>{feedback.error ? <p role="alert" className="mt-4 text-sm text-destructive">The unit feedback summary could not be loaded.</p> : feedback.isLoading || !summary ? <p role="status" className="mt-4 text-sm text-muted-foreground">Loading the unit feedback summary…</p> : summary.suppressed ? <p role="status" className="mt-4 text-sm text-muted-foreground">Withheld: {summary.display_text}</p> : <dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Average rating</dt><dd className="text-2xl font-semibold">{summary.mean_rating}</dd></div><div><dt className="text-sm text-muted-foreground">Responses counted</dt><dd className="text-2xl font-semibold">{summary.response_count}</dd></div></dl>}<Link className="mt-4 inline-block text-sm font-medium underline" to="/coordinator-portal/speaker-feedback">Read per-speaker summaries</Link></section></div>;
}
