"""Team workspaces against a real PostgreSQL (CE-WORKSPACE, design spec §15, §11).

``tests/unit/test_exercise_workspace_router.py`` proves the routes over a fake
repository. A fake repository cannot prove any of the four things that actually
keep six teams apart in a classroom, and all four are database properties:

* **The race.** Two laptops on team 3 entering at the same moment produce one
  row, because ``uq_exercise_team_workspace_dataset_team`` admits one and the
  loser's insert is discarded — not because one of them checked first.
* **Isolation.** A reset deletes this team's overlay, settings and runs and
  leaves every other team's untouched, including their seeds. Justin's
  checklist calls this out by name.
* **The seed.** Regenerated by a reset, and it is a real column with a real
  ``BIGINT`` range that a 64-bit draw would overflow.
* **"The active dataset."** Most recently uploaded wins, and the rule has to
  hold against rows whose ``uploaded_at`` values are close enough to tie.

Runs against its own scratch database, migrated to head, and dropped
afterwards; skipped where no PostgreSQL is reachable.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta

import pytest

pytest.importorskip("sqlalchemy")

import sqlalchemy as sa
from migration_harness import alembic, connected, scratch_database
from smartmatch_domain.exercise.workspace_token import (
    derive_workspace_token,
    hash_workspace_token,
)
from smartmatch_persistence.exercise import schema
from smartmatch_persistence.exercise.workspace_repository import (
    WORKSPACE_MEMBERSHIP_LOCK_KEY,
    ExerciseWorkspaceRepository,
    active_dataset,
)
from sqlalchemy import Engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session, sessionmaker

pytestmark = pytest.mark.integration

#: Not a real key, and assembled from pieces for the reason the unit file gives:
#: ``tools/scan_forbidden.py`` matches the shape of a committed credential, and
#: a test that needs an exception from that rule is a test written badly.
_SECRET = "-".join(("integration", "only", "exercise", "workspace", "key"))


@pytest.fixture
def exercise_sessions(engine: Engine) -> Iterator[sessionmaker[Session]]:
    """A session factory over a scratch database migrated to head.

    Its own database rather than the shared development one, because this file
    deletes rows: a ``DELETE FROM exercise_profile_overlay`` run against
    somebody's working database is somebody's work gone.
    """
    with scratch_database(engine) as url:
        alembic(url, "head", expect_success=True)
        with connected(url) as scratch:
            yield sessionmaker(bind=scratch, expire_on_commit=False, future=True)


def _insert_dataset(
    session: Session, *, label: str, uploaded_at: datetime | None = None, invite_limit: int = 30
) -> uuid.UUID:
    """One ``exercise_dataset`` row, written directly.

    CE-INGEST-CORE owns the repository that writes these for real; this file
    must not anticipate its shape, so it writes the columns the migration
    declares and nothing more.
    """
    dataset_id = uuid.uuid4()
    values: dict[str, object] = {
        "id": dataset_id,
        "label": label,
        "source_filename": f"{label}.csv",
        "row_count": 300,
        "checksum": uuid.uuid4().hex,
        "invite_limit": invite_limit,
    }
    if uploaded_at is not None:
        values["uploaded_at"] = uploaded_at
    session.execute(sa.insert(schema.exercise_dataset).values(**values))
    # One profile and one event, because the overlay, the saved setting and the
    # result run all carry composite foreign keys into them. Not a fixture of
    # the exercise's data — the real 300 arrive with CE-INGEST-CORE — just the
    # two rows a team's work has to hang off.
    session.execute(
        sa.insert(schema.exercise_profile).values(
            dataset_id=dataset_id,
            profile_no=1,
            display_name="A made-up person",
        )
    )
    session.execute(
        sa.insert(schema.exercise_event).values(
            dataset_id=dataset_id,
            event_key="northline",
            name="Northline Analytics",
            sequence=1,
            is_exercise_event=True,
        )
    )
    session.commit()
    return dataset_id


def _seed_of(session: Session, workspace_id: uuid.UUID) -> int:
    table = schema.exercise_team_workspace
    return int(
        session.execute(sa.select(table.c.seed).where(table.c.id == workspace_id)).scalar_one()
    )


# ---------------------------------------------------------------------------
# The active dataset
# ---------------------------------------------------------------------------


def test_no_dataset_is_a_real_answer(exercise_sessions: sessionmaker[Session]) -> None:
    with exercise_sessions() as session:
        assert active_dataset(session) is None


def test_the_most_recently_uploaded_dataset_is_the_active_one(
    exercise_sessions: sessionmaker[Session],
) -> None:
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        _insert_dataset(session, label="first", uploaded_at=now - timedelta(hours=2))
        newest = _insert_dataset(session, label="second", uploaded_at=now)
        _insert_dataset(session, label="older", uploaded_at=now - timedelta(days=9))
        found = active_dataset(session)
    assert found is not None
    assert found.id == newest
    assert found.label == "second"
    assert found.invite_limit == 30


def test_a_tie_on_upload_time_still_has_one_answer(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Two rows written in the same tick order by id, so every reader agrees."""
    stamp = datetime.now(UTC)
    with exercise_sessions() as session:
        first = _insert_dataset(session, label="a", uploaded_at=stamp)
        second = _insert_dataset(session, label="b", uploaded_at=stamp)
        found = active_dataset(session)
    assert found is not None
    assert found.id == max(first, second)


# ---------------------------------------------------------------------------
# Getting in
# ---------------------------------------------------------------------------


def test_entering_twice_returns_one_workspace(
    exercise_sessions: sessionmaker[Session],
) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="entering-twice")
        first = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        second = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        assert first == second
        count = session.execute(
            sa.select(sa.func.count()).select_from(schema.exercise_team_workspace)
        ).scalar_one()
    assert count == 1


def test_two_concurrent_entries_for_team_three_yield_one_row(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The race, run as a race rather than described as one.

    Two sessions, two open transactions, both inserting before either commits.
    PostgreSQL blocks the second on the unique index until the first commits and
    then discards it — which is what ``ON CONFLICT DO NOTHING`` means under
    concurrency — and both read back the same row.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as setup:
        dataset_id = _insert_dataset(setup, label="the-race")

    with exercise_sessions() as one, exercise_sessions() as two:
        first = repository.get_or_create_workspace(
            one, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        one.commit()
        second = repository.get_or_create_workspace(
            two, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        two.commit()

    assert first.id == second.id
    with exercise_sessions() as session:
        count = session.execute(
            sa.select(sa.func.count()).select_from(schema.exercise_team_workspace)
        ).scalar_one()
    assert count == 1


def test_the_stored_hash_matches_the_token_derived_from_the_row_that_won(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The property the whole derived-token design rests on (OQ-CE-08).

    The insert computes the hash from a candidate id that may lose the race.
    What must be true afterwards is that the hash on the *surviving* row is the
    hash of the token derived from the *surviving* id — otherwise the second
    laptop's cookie would address nothing.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="derivation")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        table = schema.exercise_team_workspace
        stored = session.execute(
            sa.select(table.c.workspace_token_hash).where(table.c.id == workspace.id)
        ).scalar_one()
        expected = hash_workspace_token(
            derive_workspace_token(secret=_SECRET, workspace_id=workspace.id)
        )
        assert stored == expected
        found = repository.find_by_token_hash(session, token_hash=expected)
    assert found == workspace


def test_rotating_the_secret_does_not_brick_a_team(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """H1. A rotated secret costs a team its cookie, never its work.

    Before the repair-on-entry this file's fix added, rotation was permanent
    damage: ``ON CONFLICT DO NOTHING`` kept the hash derived under the *old*
    secret, so a team that re-entered its number got 200 and a cookie derived
    under the *new* one, and every later request 401'd forever with no way back
    short of an operator editing the table. That contradicted ``.env.example``,
    ``workspace_token.py``'s docstring and the PR body, all three of which
    promise that re-entering the number restores the workspace.

    What must be true: the team's saved work is still there afterwards, found
    through a cookie derived under the new secret.
    """
    repository = ExerciseWorkspaceRepository()
    rotated = _SECRET + "-rotated"
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="rotation")
        before = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        _add_team_work(session, workspace_id=before.id, dataset_id=dataset_id)
        seed_before = _seed_of(session, before.id)

        # The team re-enters its number in a process booted with the new secret.
        after = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=rotated
        )
        session.commit()

        assert after.id == before.id, "the same workspace, not a new one"
        assert _child_counts(session, after.id) == (1, 1, 1), "the team's work survived"
        assert _seed_of(session, after.id) == seed_before, "a rotation is not a reset"

        new_cookie = hash_workspace_token(
            derive_workspace_token(secret=rotated, workspace_id=after.id)
        )
        assert repository.find_by_token_hash(session, token_hash=new_cookie) == after


def test_a_cookie_from_before_a_rotation_is_refused_after_the_repair(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The other half of H1, and the cost the PR body has to state.

    Repair-on-entry rewrites the stored hash, so the tab that was holding a
    cookie derived under the old secret is logged out. That is the honest
    outcome of rotating a key and it loses nothing: the team re-enters its
    number and is back in the same workspace, as the test above proves.
    """
    repository = ExerciseWorkspaceRepository()
    rotated = _SECRET + "-rotated"
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="rotation-old-cookie")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
        old_cookie = hash_workspace_token(
            derive_workspace_token(secret=_SECRET, workspace_id=workspace.id)
        )
        assert repository.find_by_token_hash(session, token_hash=old_cookie) == workspace

        repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=rotated
        )
        session.commit()

        assert repository.find_by_token_hash(session, token_hash=old_cookie) is None


def test_entry_under_an_unchanged_secret_rewrites_nothing(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The repair is guarded, so the ordinary path is still one read.

    ``WHERE ... AND workspace_token_hash != expected`` means an entry that
    changes nothing updates no row — which is what keeps six teams entering
    their numbers all lesson from writing to the same row every time.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="no-needless-write")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=5, workspace_secret=_SECRET
        )
        session.commit()
        repaired = repository.repair_token_hash(
            session, workspace_id=workspace.id, workspace_secret=_SECRET
        )
    assert repaired is False


def test_an_existing_cookie_keeps_its_old_dataset_after_a_new_upload(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """M2. Design spec §3, pinned, because the PR body claimed the opposite.

    An upload does not re-point live workspaces. A team holding a cookie from
    before it keeps working in its old dataset until the instructor re-points,
    and a re-point resets every team. What the review corrected is the claim
    that such a cookie 401s — it does not, and scoping the lookup to the active
    dataset to *make* it 401 would break the spec's stated behaviour.
    """
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        first_dataset = _insert_dataset(
            session, label="round-one", uploaded_at=now - timedelta(hours=1)
        )
        workspace = repository.get_or_create_workspace(
            session, dataset_id=first_dataset, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        cookie = hash_workspace_token(
            derive_workspace_token(secret=_SECRET, workspace_id=workspace.id)
        )

        second_dataset = _insert_dataset(session, label="round-two", uploaded_at=now)
        assert active_dataset(session) is not None
        assert active_dataset(session).id == second_dataset  # type: ignore[union-attr]

        # The old cookie still resolves, to its own dataset.
        still_there = repository.find_by_token_hash(session, token_hash=cookie)
        assert still_there == workspace
        assert still_there is not None
        assert still_there.dataset_label == "round-one"

        # A *new* entry for the same team number lands on the newest dataset,
        # in a second workspace row. CE-INSTRUCTOR owns whether that is right;
        # this test records that it is what happens today.
        fresh = repository.get_or_create_workspace(
            session, dataset_id=second_dataset, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
    assert fresh.id != workspace.id
    assert fresh.dataset_label == "round-two"


def test_an_unknown_token_hash_finds_nothing(exercise_sessions: sessionmaker[Session]) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="unknown-token")
        repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=1, workspace_secret=_SECRET
        )
        session.commit()
        assert repository.find_by_token_hash(session, token_hash="0" * 64) is None
        # A token derived under a different secret is just as unknown.
        other = hash_workspace_token(
            derive_workspace_token(secret=_SECRET + "-rotated", workspace_id=uuid.uuid4())
        )
        assert repository.find_by_token_hash(session, token_hash=other) is None


def test_each_team_gets_its_own_workspace_and_its_own_seed(
    exercise_sessions: sessionmaker[Session],
) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="six-teams")
        workspaces = {
            team: repository.get_or_create_workspace(
                session, dataset_id=dataset_id, team_number=team, workspace_secret=_SECRET
            )
            for team in range(1, 7)
        }
        session.commit()
        seeds = {team: _seed_of(session, ws.id) for team, ws in workspaces.items()}
    assert len({ws.id for ws in workspaces.values()}) == 6
    assert len(set(seeds.values())) == 6, "six teams, six independent chance elements"
    for seed in seeds.values():
        assert 0 <= seed < 2**63, "BIGINT is signed"


# ---------------------------------------------------------------------------
# The reset (design spec §11)
# ---------------------------------------------------------------------------


def _add_team_work(session: Session, *, workspace_id: uuid.UUID, dataset_id: uuid.UUID) -> None:
    """One overlay row, one saved setting and one result run for a team.

    Written directly rather than through the repositories that will own them
    (CE-SIMULATION, CE-INSTRUCTOR), because what is being tested is that a
    reset deletes them, not how they arrive.
    """
    session.execute(
        sa.insert(schema.exercise_profile_overlay).values(
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            profile_no=1,
            card_career_goal="PLACEHOLDER (OQ-CE-01)",
        )
    )
    session.execute(
        sa.insert(schema.exercise_saved_setting).values(
            id=uuid.uuid4(),
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            event_key="northline",
            name="even weights",
            weights={"same_major": 0.25},
        )
    )
    session.execute(
        sa.insert(schema.exercise_result_run).values(
            id=uuid.uuid4(),
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            event_key="northline",
            round=1,
            seats_empty=52,
            email_everyone={},
        )
    )
    session.execute(
        sa.update(schema.exercise_team_workspace)
        .where(schema.exercise_team_workspace.c.id == workspace_id)
        .values(asking_choice="small_reward", refreshed_at=datetime.now(UTC))
    )
    session.commit()


def _child_counts(session: Session, workspace_id: uuid.UUID) -> tuple[int, int, int]:
    return tuple(  # type: ignore[return-value]
        session.execute(
            sa.select(sa.func.count())
            .select_from(table)
            .where(table.c.workspace_id == workspace_id)
        ).scalar_one()
        for table in (
            schema.exercise_profile_overlay,
            schema.exercise_saved_setting,
            schema.exercise_result_run,
        )
    )


def test_a_reset_clears_one_team_and_nothing_else(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Justin's checklist line, as an assertion about two teams' rows.

    The point is not only that team 1 is empty afterwards. It is that team 2 is
    untouched — its overlay, its settings, its run, *and* its seed, which a
    reset that regenerated seeds by dataset rather than by workspace would have
    changed without deleting anything visible.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-isolation")
        first = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=1, workspace_secret=_SECRET
        )
        second = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        _add_team_work(session, workspace_id=first.id, dataset_id=dataset_id)
        _add_team_work(session, workspace_id=second.id, dataset_id=dataset_id)

        first_seed_before = _seed_of(session, first.id)
        second_seed_before = _seed_of(session, second.id)
        assert _child_counts(session, first.id) == (1, 1, 1)

        repository.reset_team(session, workspace_id=first.id)
        session.commit()

        assert _child_counts(session, first.id) == (0, 0, 0)
        assert _child_counts(session, second.id) == (1, 1, 1)
        assert _seed_of(session, first.id) != first_seed_before
        assert _seed_of(session, second.id) == second_seed_before

        table = schema.exercise_team_workspace
        row = session.execute(
            sa.select(
                table.c.asking_choice, table.c.refreshed_at, table.c.workspace_token_hash
            ).where(table.c.id == first.id)
        ).one()
    assert row.asking_choice is None
    assert row.refreshed_at is None
    assert row.workspace_token_hash == hash_workspace_token(
        derive_workspace_token(secret=_SECRET, workspace_id=first.id)
    ), "a reset keeps the team's token: it clears work, it does not log anybody out"


def test_a_reset_keeps_the_workspace_row(exercise_sessions: sessionmaker[Session]) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-keeps-row")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
        repository.reset_team(session, workspace_id=workspace.id)
        session.commit()
        again = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
    assert again == workspace


def test_a_reset_of_an_unknown_workspace_changes_nothing(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """A workspace id that names no row is not an error and not a wildcard."""
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-unknown")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=5, workspace_secret=_SECRET
        )
        session.commit()
        _add_team_work(session, workspace_id=workspace.id, dataset_id=dataset_id)
        seed_before = _seed_of(session, workspace.id)

        repository.reset_team(session, workspace_id=uuid.uuid4())
        session.commit()

        assert _child_counts(session, workspace.id) == (1, 1, 1)
        assert _seed_of(session, workspace.id) == seed_before


# ---------------------------------------------------------------------------
# What a read may carry
# ---------------------------------------------------------------------------


def test_a_workspace_read_carries_no_seed_and_no_token_hash(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The columns are named explicitly, so the dataclass cannot grow them."""
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="read-shape", invite_limit=25)
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=6, workspace_secret=_SECRET
        )
        session.commit()
    fields = set(vars(type(workspace)).get("__slots__", ()))
    assert fields == {"id", "dataset_id", "team_number", "dataset_label", "invite_limit"}
    assert workspace.invite_limit == 25
    assert workspace.dataset_label == "read-shape"


# ---------------------------------------------------------------------------
# Where an entry lands (owner ruling, 2026-09-19)
# ---------------------------------------------------------------------------


def _created_at(session: Session, workspace_id: uuid.UUID, *, when: datetime) -> None:
    """Backdate a workspace row, so the tie-break can be tested without sleeping.

    ``created_at`` is a server default, which means every row written inside one
    test has the same-ish stamp and an ordering assertion over them would prove
    the ``id`` tie-break rather than the rule. Written directly for the reason
    ``_insert_dataset`` gives: the repository owns no clock parameter and should
    not grow one for a test.
    """
    table = schema.exercise_team_workspace
    session.execute(sa.update(table).where(table.c.id == workspace_id).values(created_at=when))
    session.commit()


def test_a_team_that_has_a_workspace_re_enters_that_one_not_the_newest_file(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The ruling itself: an upload does not move a team, and neither does reload.

    Team 3 enters on the old file. The instructor uploads a new one — design
    spec §3: that moves nobody. Team 3 presses reload. Before the ruling this
    handed it a second, empty workspace on the new file and its work looked
    gone; now it is handed the same row back.
    """
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        old = _insert_dataset(session, label="old-file", uploaded_at=now - timedelta(hours=2))
        first = repository.get_or_create_workspace(
            session, dataset_id=old, team_number=3, workspace_secret=_SECRET
        )
        session.commit()

        newest = _insert_dataset(session, label="new-file", uploaded_at=now)
        # The newest upload really is newer — the fallback would have chosen it.
        found = active_dataset(session)
        assert found is not None and found.id == newest

        assert repository.entry_dataset_for(session, team_number=3) == old
        again = repository.get_or_create_workspace(
            session, dataset_id=old, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        assert again == first
        count = session.execute(
            sa.select(sa.func.count()).select_from(schema.exercise_team_workspace)
        ).scalar_one()
    assert count == 1, "a reload after an upload must not mint a second workspace"


def test_a_legacy_team_on_two_files_lands_on_its_most_recent_workspace(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Branch 2. Nothing creates this state now; rows from before the ruling are in it.

    The tie-break is the most recently created workspace row — the file the
    team most recently entered, which is the one whose work it was last looking
    at. Asserted against the *older* row being the one on the newest data file,
    so a rule that secretly still preferred the newest upload would fail here.
    """
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        first_file = _insert_dataset(session, label="file-a", uploaded_at=now - timedelta(hours=3))
        second_file = _insert_dataset(session, label="file-b", uploaded_at=now)
        on_second = repository.get_or_create_workspace(
            session, dataset_id=second_file, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
        on_first = repository.get_or_create_workspace(
            session, dataset_id=first_file, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
        # The row on the *older* file is the more recently created one.
        _created_at(session, on_second.id, when=now - timedelta(hours=1))
        _created_at(session, on_first.id, when=now)

        assert repository.entry_dataset_for(session, team_number=4) == first_file


def test_a_brand_new_team_joins_the_file_the_other_teams_are_on(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Branch 3. Team 5 arriving late lands in the lesson, not in a file nobody sees."""
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        in_use = _insert_dataset(session, label="in-use", uploaded_at=now - timedelta(hours=2))
        uploaded_later = _insert_dataset(session, label="not-in-use-yet", uploaded_at=now)
        for team_number in (1, 2, 3):
            repository.get_or_create_workspace(
                session, dataset_id=in_use, team_number=team_number, workspace_secret=_SECRET
            )
        session.commit()

        assert repository.entry_dataset_for(session, team_number=5) == in_use
        assert repository.entry_dataset_for(session, team_number=5) != uploaded_later


def test_the_first_team_of_the_lesson_gets_the_newest_file_under_the_lock(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Branch 3's other half, decided here rather than by the caller (PR #186).

    With no classroom to join, the newest upload is the answer — and it is read
    inside the advisory lock this method already holds. It used to return
    ``None`` so that the route could use its ``ActiveDataset`` dependency, which
    had resolved *before* the lock was taken; an upload committing in that
    window put the first team of the lesson in a file that was no longer the
    newest, and nothing afterwards disagrees with that choice because every
    later team joins whatever this one picked.

    The ordering under test is :func:`active_dataset`'s own — most recently
    uploaded wins — so the two answers cannot drift.
    """
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        _insert_dataset(session, label="older-upload", uploaded_at=now - timedelta(hours=1))
        newest = _insert_dataset(session, label="newest-upload", uploaded_at=now)
        session.commit()
        chosen = repository.entry_dataset_for(session, team_number=1)
    assert chosen == newest
    newest_summary = None
    with exercise_sessions() as reader:
        newest_summary = active_dataset(reader)
    assert newest_summary is not None
    assert chosen == newest_summary.id


def test_with_no_data_file_at_all_there_is_still_nothing_to_join(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """``None`` now means exactly one thing, and the caller's 409 answers it."""
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        assert repository.entry_dataset_for(session, team_number=1) is None


def test_a_re_point_is_what_moves_a_team_and_entry_then_follows_it(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The ruling's exception, stated as the behaviour it is.

    "Only an instructor re-point moves a team" is a claim about this function
    as much as about the instructor's, so the move is performed here — by the
    statement a re-point runs — and the entry rule is asked again afterwards.
    """
    repository = ExerciseWorkspaceRepository()
    table = schema.exercise_team_workspace
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        old = _insert_dataset(session, label="before-repoint", uploaded_at=now - timedelta(hours=2))
        target = _insert_dataset(session, label="after-repoint", uploaded_at=now)
        workspace = repository.get_or_create_workspace(
            session, dataset_id=old, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        assert repository.entry_dataset_for(session, team_number=2) == old

        session.execute(
            sa.update(table).where(table.c.id == workspace.id).values(dataset_id=target)
        )
        session.commit()

        assert repository.entry_dataset_for(session, team_number=2) == target


def test_one_teams_entry_does_not_decide_another_teams_file(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Branch 1 beats branch 3: a team with a workspace is never moved by a newcomer."""
    repository = ExerciseWorkspaceRepository()
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        first_file = _insert_dataset(session, label="team-one-file", uploaded_at=now - timedelta(1))
        second_file = _insert_dataset(session, label="team-two-file", uploaded_at=now)
        repository.get_or_create_workspace(
            session, dataset_id=first_file, team_number=1, workspace_secret=_SECRET
        )
        session.commit()
        repository.get_or_create_workspace(
            session, dataset_id=second_file, team_number=2, workspace_secret=_SECRET
        )
        session.commit()

        assert repository.entry_dataset_for(session, team_number=1) == first_file
        assert repository.entry_dataset_for(session, team_number=2) == second_file
        # And the newcomer joins the most recently created workspace's file.
        assert repository.entry_dataset_for(session, team_number=6) == second_file


# ---------------------------------------------------------------------------
# The entry decision and the insert are one atomic step (review round 1)
# ---------------------------------------------------------------------------


def _try_lock(session: Session) -> bool:
    """Whether the workspace-membership key is free, from this session's view.

    ``pg_try_advisory_xact_lock`` rather than a blocking acquire, so a probe
    can ask "is it held?" without becoming the thing that waits. The caller
    rolls back immediately: a successful try has *taken* the lock, and leaving
    it taken would make the next probe lie.
    """
    held = session.execute(
        sa.select(sa.func.pg_try_advisory_xact_lock(WORKSPACE_MEMBERSHIP_LOCK_KEY))
    ).scalar_one()
    session.rollback()
    return bool(held)


def test_choosing_the_entry_data_file_takes_the_membership_lock(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The decision is made *under* the lock, not before it.

    Without this, the entry path had a race with a shape a classroom produces
    on its own. Team 3 presses enter; :meth:`entry_dataset_for` reads, unlocked,
    and answers "data file A"; the instructor's re-point — holding the lock —
    moves team 3 to B and commits; the entry then takes the lock and inserts a
    **new** ``(A, team 3)`` row, because the row it read has moved out from
    under it. Team 3 now holds two workspaces, the newest-created tie-break
    pins it to A forever, the re-point silently moved nobody, and every
    instructor action without an explicit ``dataset_id`` refuses with "the
    teams are split across more than one data file".

    Asserted by holding the key from a second connection and giving the reader
    a short ``lock_timeout``: it is refused, quickly and deterministically,
    rather than waiting on a sleep. Without the fix it takes no lock at all and
    returns an answer.
    """
    with exercise_sessions() as holder, exercise_sessions() as entering:
        dataset_id = _insert_dataset(holder, label="decision-under-lock")
        ExerciseWorkspaceRepository().get_or_create_workspace(
            holder, dataset_id=dataset_id, team_number=1, workspace_secret=_SECRET
        )
        holder.commit()

        # A re-point, or another entry, is mid-transaction and holds the key.
        holder.execute(sa.select(sa.func.pg_advisory_xact_lock(WORKSPACE_MEMBERSHIP_LOCK_KEY)))

        entering.execute(sa.text("SET LOCAL lock_timeout = '250ms'"))
        with pytest.raises(SQLAlchemyError) as refused:
            ExerciseWorkspaceRepository().entry_dataset_for(entering, team_number=3)
        entering.rollback()
        holder.rollback()

    assert "lock timeout" in str(refused.value).lower()


def test_the_decision_and_the_insert_share_one_holding_of_the_lock(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """One transaction, one holding — no window between deciding and inserting.

    Two locks taken and released in turn would leave exactly the gap the race
    above needs. What is pinned here is that the key is held *continuously*
    from the moment the data file is chosen until the workspace row is
    committed, and that it is then released. The second acquire inside
    ``get_or_create_workspace`` is harmless because a PostgreSQL advisory lock
    is re-entrant within one transaction.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as writer, exercise_sessions() as probe:
        dataset_id = _insert_dataset(writer, label="one-holding")
        assert _try_lock(probe) is True, "nothing may hold the key at the start"

        chosen = repository.entry_dataset_for(writer, team_number=4)
        assert _try_lock(probe) is False, "the decision must be made holding the key"

        repository.get_or_create_workspace(
            writer,
            dataset_id=chosen if chosen is not None else dataset_id,
            team_number=4,
            workspace_secret=_SECRET,
        )
        assert _try_lock(probe) is False, "the key must still be held for the insert"

        writer.commit()
        assert _try_lock(probe) is True, "committing releases it"


def test_an_entry_after_a_committed_repoint_joins_the_team_where_it_was_moved(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The outcome the lock protects, stated as behaviour rather than as timing.

    Once the re-point has committed, the next entry for that team sees the
    moved row and opens it — one workspace, on the target file, and no second
    row minted against the file the team has just been moved off.
    """
    repository = ExerciseWorkspaceRepository()
    table = schema.exercise_team_workspace
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        old = _insert_dataset(session, label="pre-repoint", uploaded_at=now - timedelta(hours=2))
        target = _insert_dataset(session, label="post-repoint", uploaded_at=now)
        workspace = repository.get_or_create_workspace(
            session, dataset_id=old, team_number=3, workspace_secret=_SECRET
        )
        session.commit()

        # What a re-point does to this row, committed before the entry runs.
        session.execute(
            sa.update(table).where(table.c.id == workspace.id).values(dataset_id=target)
        )
        session.commit()

        chosen = repository.entry_dataset_for(session, team_number=3)
        assert chosen == target
        again = repository.get_or_create_workspace(
            session, dataset_id=target, team_number=3, workspace_secret=_SECRET
        )
        session.commit()

        assert again.id == workspace.id, "the team keeps its row, and its cookie"
        rows = session.execute(
            sa.select(sa.func.count()).select_from(table).where(table.c.team_number == 3)
        ).scalar_one()
    assert rows == 1, "an entry after a re-point must not mint a second workspace"
