"""Team workspaces against a real PostgreSQL (CE-WORKSPACE, design spec §15, §11).

``tests/unit/test_exercise_workspace_router.py`` proves the routes over a fake
repository. A fake repository cannot prove any of the four things that actually
keep six teams apart in a classroom, and all four are database properties:

* **The race.** Two laptops on team 3 entering at the same moment produce one
  row, because ``uq_exercise_team_workspace_dataset_team`` admits one and the
  loser's insert is discarded — not because one of them checked first.
* **Isolation.** A reset deletes this team's overlay, settings and runs and
  leaves every other team's untouched, including their seeds. Justin's
  checklist calls this out by name.
* **The seed.** Regenerated by a reset, and it is a real column with a real
  ``BIGINT`` range that a 64-bit draw would overflow.
* **"The active dataset."** Most recently uploaded wins, and the rule has to
  hold against rows whose ``uploaded_at`` values are close enough to tie.

Runs against its own scratch database, migrated to head, and dropped
afterwards; skipped where no PostgreSQL is reachable.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta

import pytest

pytest.importorskip("sqlalchemy")

import sqlalchemy as sa
from migration_harness import alembic, connected, scratch_database
from smartmatch_domain.exercise.workspace_token import (
    derive_workspace_token,
    hash_workspace_token,
)
from smartmatch_persistence.exercise import schema
from smartmatch_persistence.exercise.workspace_repository import (
    ExerciseWorkspaceRepository,
    active_dataset,
)
from sqlalchemy import Engine
from sqlalchemy.orm import Session, sessionmaker

pytestmark = pytest.mark.integration

#: Not a real key, and assembled from pieces for the reason the unit file gives:
#: ``tools/scan_forbidden.py`` matches the shape of a committed credential, and
#: a test that needs an exception from that rule is a test written badly.
_SECRET = "-".join(("integration", "only", "exercise", "workspace", "key"))


@pytest.fixture
def exercise_sessions(engine: Engine) -> Iterator[sessionmaker[Session]]:
    """A session factory over a scratch database migrated to head.

    Its own database rather than the shared development one, because this file
    deletes rows: a ``DELETE FROM exercise_profile_overlay`` run against
    somebody's working database is somebody's work gone.
    """
    with scratch_database(engine) as url:
        alembic(url, "head", expect_success=True)
        with connected(url) as scratch:
            yield sessionmaker(bind=scratch, expire_on_commit=False, future=True)


def _insert_dataset(
    session: Session, *, label: str, uploaded_at: datetime | None = None, invite_limit: int = 30
) -> uuid.UUID:
    """One ``exercise_dataset`` row, written directly.

    CE-INGEST-CORE owns the repository that writes these for real; this file
    must not anticipate its shape, so it writes the columns the migration
    declares and nothing more.
    """
    dataset_id = uuid.uuid4()
    values: dict[str, object] = {
        "id": dataset_id,
        "label": label,
        "source_filename": f"{label}.csv",
        "row_count": 300,
        "checksum": uuid.uuid4().hex,
        "invite_limit": invite_limit,
    }
    if uploaded_at is not None:
        values["uploaded_at"] = uploaded_at
    session.execute(sa.insert(schema.exercise_dataset).values(**values))
    # One profile and one event, because the overlay, the saved setting and the
    # result run all carry composite foreign keys into them. Not a fixture of
    # the exercise's data — the real 300 arrive with CE-INGEST-CORE — just the
    # two rows a team's work has to hang off.
    session.execute(
        sa.insert(schema.exercise_profile).values(
            dataset_id=dataset_id,
            profile_no=1,
            display_name="A made-up person",
        )
    )
    session.execute(
        sa.insert(schema.exercise_event).values(
            dataset_id=dataset_id,
            event_key="northline",
            name="Northline Analytics",
            sequence=1,
            is_exercise_event=True,
        )
    )
    session.commit()
    return dataset_id


def _seed_of(session: Session, workspace_id: uuid.UUID) -> int:
    table = schema.exercise_team_workspace
    return int(
        session.execute(sa.select(table.c.seed).where(table.c.id == workspace_id)).scalar_one()
    )


# ---------------------------------------------------------------------------
# The active dataset
# ---------------------------------------------------------------------------


def test_no_dataset_is_a_real_answer(exercise_sessions: sessionmaker[Session]) -> None:
    with exercise_sessions() as session:
        assert active_dataset(session) is None


def test_the_most_recently_uploaded_dataset_is_the_active_one(
    exercise_sessions: sessionmaker[Session],
) -> None:
    now = datetime.now(UTC)
    with exercise_sessions() as session:
        _insert_dataset(session, label="first", uploaded_at=now - timedelta(hours=2))
        newest = _insert_dataset(session, label="second", uploaded_at=now)
        _insert_dataset(session, label="older", uploaded_at=now - timedelta(days=9))
        found = active_dataset(session)
    assert found is not None
    assert found.id == newest
    assert found.label == "second"
    assert found.invite_limit == 30


def test_a_tie_on_upload_time_still_has_one_answer(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Two rows written in the same tick order by id, so every reader agrees."""
    stamp = datetime.now(UTC)
    with exercise_sessions() as session:
        first = _insert_dataset(session, label="a", uploaded_at=stamp)
        second = _insert_dataset(session, label="b", uploaded_at=stamp)
        found = active_dataset(session)
    assert found is not None
    assert found.id == max(first, second)


# ---------------------------------------------------------------------------
# Getting in
# ---------------------------------------------------------------------------


def test_entering_twice_returns_one_workspace(
    exercise_sessions: sessionmaker[Session],
) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="entering-twice")
        first = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        second = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        session.commit()
        assert first == second
        count = session.execute(
            sa.select(sa.func.count()).select_from(schema.exercise_team_workspace)
        ).scalar_one()
    assert count == 1


def test_two_concurrent_entries_for_team_three_yield_one_row(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The race, run as a race rather than described as one.

    Two sessions, two open transactions, both inserting before either commits.
    PostgreSQL blocks the second on the unique index until the first commits and
    then discards it — which is what ``ON CONFLICT DO NOTHING`` means under
    concurrency — and both read back the same row.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as setup:
        dataset_id = _insert_dataset(setup, label="the-race")

    with exercise_sessions() as one, exercise_sessions() as two:
        first = repository.get_or_create_workspace(
            one, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        one.commit()
        second = repository.get_or_create_workspace(
            two, dataset_id=dataset_id, team_number=3, workspace_secret=_SECRET
        )
        two.commit()

    assert first.id == second.id
    with exercise_sessions() as session:
        count = session.execute(
            sa.select(sa.func.count()).select_from(schema.exercise_team_workspace)
        ).scalar_one()
    assert count == 1


def test_the_stored_hash_matches_the_token_derived_from_the_row_that_won(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The property the whole derived-token design rests on (OQ-CE-08).

    The insert computes the hash from a candidate id that may lose the race.
    What must be true afterwards is that the hash on the *surviving* row is the
    hash of the token derived from the *surviving* id — otherwise the second
    laptop's cookie would address nothing.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="derivation")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        table = schema.exercise_team_workspace
        stored = session.execute(
            sa.select(table.c.workspace_token_hash).where(table.c.id == workspace.id)
        ).scalar_one()
        expected = hash_workspace_token(
            derive_workspace_token(secret=_SECRET, workspace_id=workspace.id)
        )
        assert stored == expected
        found = repository.find_by_token_hash(session, token_hash=expected)
    assert found == workspace


def test_an_unknown_token_hash_finds_nothing(exercise_sessions: sessionmaker[Session]) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="unknown-token")
        repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=1, workspace_secret=_SECRET
        )
        session.commit()
        assert repository.find_by_token_hash(session, token_hash="0" * 64) is None
        # A token derived under a different secret is just as unknown.
        other = hash_workspace_token(
            derive_workspace_token(secret=_SECRET + "-rotated", workspace_id=uuid.uuid4())
        )
        assert repository.find_by_token_hash(session, token_hash=other) is None


def test_each_team_gets_its_own_workspace_and_its_own_seed(
    exercise_sessions: sessionmaker[Session],
) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="six-teams")
        workspaces = {
            team: repository.get_or_create_workspace(
                session, dataset_id=dataset_id, team_number=team, workspace_secret=_SECRET
            )
            for team in range(1, 7)
        }
        session.commit()
        seeds = {team: _seed_of(session, ws.id) for team, ws in workspaces.items()}
    assert len({ws.id for ws in workspaces.values()}) == 6
    assert len(set(seeds.values())) == 6, "six teams, six independent chance elements"
    for seed in seeds.values():
        assert 0 <= seed < 2**63, "BIGINT is signed"


# ---------------------------------------------------------------------------
# The reset (design spec §11)
# ---------------------------------------------------------------------------


def _add_team_work(session: Session, *, workspace_id: uuid.UUID, dataset_id: uuid.UUID) -> None:
    """One overlay row, one saved setting and one result run for a team.

    Written directly rather than through the repositories that will own them
    (CE-SIMULATION, CE-INSTRUCTOR), because what is being tested is that a
    reset deletes them, not how they arrive.
    """
    session.execute(
        sa.insert(schema.exercise_profile_overlay).values(
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            profile_no=1,
            card_career_goal="PLACEHOLDER (OQ-CE-01)",
        )
    )
    session.execute(
        sa.insert(schema.exercise_saved_setting).values(
            id=uuid.uuid4(),
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            event_key="northline",
            name="even weights",
            weights={"same_major": 0.25},
        )
    )
    session.execute(
        sa.insert(schema.exercise_result_run).values(
            id=uuid.uuid4(),
            workspace_id=workspace_id,
            dataset_id=dataset_id,
            event_key="northline",
            round=1,
            seats_empty=52,
            email_everyone={},
        )
    )
    session.execute(
        sa.update(schema.exercise_team_workspace)
        .where(schema.exercise_team_workspace.c.id == workspace_id)
        .values(asking_choice="small_reward", refreshed_at=datetime.now(UTC))
    )
    session.commit()


def _child_counts(session: Session, workspace_id: uuid.UUID) -> tuple[int, int, int]:
    return tuple(  # type: ignore[return-value]
        session.execute(
            sa.select(sa.func.count())
            .select_from(table)
            .where(table.c.workspace_id == workspace_id)
        ).scalar_one()
        for table in (
            schema.exercise_profile_overlay,
            schema.exercise_saved_setting,
            schema.exercise_result_run,
        )
    )


def test_a_reset_clears_one_team_and_nothing_else(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """Justin's checklist line, as an assertion about two teams' rows.

    The point is not only that team 1 is empty afterwards. It is that team 2 is
    untouched — its overlay, its settings, its run, *and* its seed, which a
    reset that regenerated seeds by dataset rather than by workspace would have
    changed without deleting anything visible.
    """
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-isolation")
        first = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=1, workspace_secret=_SECRET
        )
        second = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=2, workspace_secret=_SECRET
        )
        session.commit()
        _add_team_work(session, workspace_id=first.id, dataset_id=dataset_id)
        _add_team_work(session, workspace_id=second.id, dataset_id=dataset_id)

        first_seed_before = _seed_of(session, first.id)
        second_seed_before = _seed_of(session, second.id)
        assert _child_counts(session, first.id) == (1, 1, 1)

        repository.reset_team(session, workspace_id=first.id)
        session.commit()

        assert _child_counts(session, first.id) == (0, 0, 0)
        assert _child_counts(session, second.id) == (1, 1, 1)
        assert _seed_of(session, first.id) != first_seed_before
        assert _seed_of(session, second.id) == second_seed_before

        table = schema.exercise_team_workspace
        row = session.execute(
            sa.select(
                table.c.asking_choice, table.c.refreshed_at, table.c.workspace_token_hash
            ).where(table.c.id == first.id)
        ).one()
    assert row.asking_choice is None
    assert row.refreshed_at is None
    assert row.workspace_token_hash == hash_workspace_token(
        derive_workspace_token(secret=_SECRET, workspace_id=first.id)
    ), "a reset keeps the team's token: it clears work, it does not log anybody out"


def test_a_reset_keeps_the_workspace_row(exercise_sessions: sessionmaker[Session]) -> None:
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-keeps-row")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
        repository.reset_team(session, workspace_id=workspace.id)
        session.commit()
        again = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=4, workspace_secret=_SECRET
        )
        session.commit()
    assert again == workspace


def test_a_reset_of_an_unknown_workspace_changes_nothing(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """A workspace id that names no row is not an error and not a wildcard."""
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="reset-unknown")
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=5, workspace_secret=_SECRET
        )
        session.commit()
        _add_team_work(session, workspace_id=workspace.id, dataset_id=dataset_id)
        seed_before = _seed_of(session, workspace.id)

        repository.reset_team(session, workspace_id=uuid.uuid4())
        session.commit()

        assert _child_counts(session, workspace.id) == (1, 1, 1)
        assert _seed_of(session, workspace.id) == seed_before


# ---------------------------------------------------------------------------
# What a read may carry
# ---------------------------------------------------------------------------


def test_a_workspace_read_carries_no_seed_and_no_token_hash(
    exercise_sessions: sessionmaker[Session],
) -> None:
    """The columns are named explicitly, so the dataclass cannot grow them."""
    repository = ExerciseWorkspaceRepository()
    with exercise_sessions() as session:
        dataset_id = _insert_dataset(session, label="read-shape", invite_limit=25)
        workspace = repository.get_or_create_workspace(
            session, dataset_id=dataset_id, team_number=6, workspace_secret=_SECRET
        )
        session.commit()
    fields = set(vars(type(workspace)).get("__slots__", ()))
    assert fields == {"id", "dataset_id", "team_number", "dataset_label", "invite_limit"}
    assert workspace.invite_limit == 25
    assert workspace.dataset_label == "read-shape"
