import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock3, MessageSquareText } from "lucide-react";
import { addSpeakerEventNote, correctSpeakerEvent, fetchSpeakerEvent, fetchSpeakerEvents, getConfiguredUnitId, transitionSpeakerEvent, type SpeakerEventRecord, type SpeakerEventStatus } from "../../lib/api";
import { usePrincipalKey } from "./PrincipalQueryProvider";

const labels: Record<SpeakerEventStatus, string> = { not_emailed_yet: "Not Emailed Yet", awaiting_response: "Awaiting Response", declined: "Declined", ready_for_handoff: "Ready for Handoff", handed_off: "Handed Off", awaiting_final_confirmation: "Awaiting Final Confirmation", confirmed: "Confirmed", withdrawn: "Withdrawn", attended: "Attended", did_not_attend: "Did Not Attend", event_cancelled: "Event Cancelled" };
const connectorActions: Partial<Record<SpeakerEventStatus, Array<[SpeakerEventStatus,string]>>> = { not_emailed_yet: [["awaiting_response","Mark outside email sent"]], awaiting_response: [["ready_for_handoff","Record interest"],["declined","Record decline"]], ready_for_handoff: [["handed_off","Hand off to Event Host"]] };
const hostActions: Partial<Record<SpeakerEventStatus, Array<[SpeakerEventStatus,string]>>> = { handed_off: [["awaiting_final_confirmation","Request final confirmation"]], awaiting_final_confirmation: [["confirmed","Record confirmation"],["withdrawn","Record withdrawal"]], confirmed: [["attended","Check in"],["withdrawn","Record withdrawal"]] };

export function SpeakerEventsBoard({ role }: { role: "connector" | "host" }) {
  const unitId = getConfiguredUnitId(); const principalKey = usePrincipalKey(); const client = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [note, setNote] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [correctionStatus, setCorrectionStatus] = useState<SpeakerEventStatus>("not_emailed_yet");
  const [statusFilter, setStatusFilter] = useState<SpeakerEventStatus | "all">("all");
  const listKey = [principalKey, "speaker-events", unitId] as const;
  const list = useQuery({ queryKey: listKey, queryFn: () => fetchSpeakerEvents(unitId!), enabled: Boolean(principalKey && unitId) });
  const detail = useQuery({ queryKey: [principalKey, "speaker-event", unitId, selectedId], queryFn: () => fetchSpeakerEvent(unitId!, selectedId!), enabled: Boolean(principalKey && unitId && selectedId) });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: listKey }), client.invalidateQueries({ queryKey: [principalKey, "speaker-event", unitId, selectedId] })]); };
  const transition = useMutation({ mutationFn: ({ record, status }: { record: SpeakerEventRecord; status: SpeakerEventStatus }) => transitionSpeakerEvent(unitId!, record.id, status, record.version), onSuccess: refresh });
  const addNote = useMutation({ mutationFn: () => addSpeakerEventNote(unitId!, selectedId!, note), onSuccess: async () => { setNote(""); await refresh(); } });
  const correct = useMutation({ mutationFn: (record: SpeakerEventRecord) => correctSpeakerEvent(unitId!, record.id, correctionStatus, record.version, correctionReason), onSuccess: async () => { setCorrectionReason(""); await refresh(); } });
  if (!unitId) return <section className="rounded-2xl border bg-card p-8"><h1 className="text-3xl">{role === "connector" ? "Invitations" : "Speaker handoffs"}</h1><p className="mt-2 text-muted-foreground">Sign in with an authorized unit to view speaker-event records.</p></section>;
  const allRecords = list.data ?? []; const records = statusFilter === "all" ? allRecords : allRecords.filter((record) => record.status === statusFilter); const selected = detail.data ?? allRecords.find((record) => record.id === selectedId);
  const actions = selected ? (role === "connector" ? connectorActions : hostActions)[selected.status] ?? [] : [];
  return <div className="space-y-6"><header><h1 className="text-3xl font-semibold">{role === "connector" ? "Invitations" : "Speaker handoffs"}</h1><p className="mt-2 text-muted-foreground">{role === "connector" ? "Track outreach completed outside Smart Match and hand interested speakers to Event Hosts." : "Request final confirmation and record attendance after a Speaker Connector hands someone off."}</p></header>
    <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl">Speaker-event list</h2><label className="text-sm">Status <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as SpeakerEventStatus | "all")} className="ml-2 rounded-lg border bg-input-background px-2 py-1.5"><option value="all">All</option>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{list.isLoading ? <p className="mt-4">Loading invitations…</p> : list.error ? <p role="alert" className="mt-4 text-destructive">{list.error instanceof Error ? list.error.message : "Invitations could not be loaded."}</p> : records.length ? <div className="mt-4 space-y-2">{records.map((record) => <button key={record.id} onClick={() => setSelectedId(record.id)} className={`w-full rounded-xl border p-4 text-left ${selectedId === record.id ? "border-primary bg-primary/5" : "hover:bg-muted/50"}`}><p className="font-semibold">{record.speaker_name}</p><p className="text-sm text-muted-foreground">{record.event_title}</p><span className="mt-2 inline-block rounded-full bg-muted px-2 py-1 text-xs font-semibold">{labels[record.status]}</span></button>)}</div> : <div className="mt-6 text-center text-sm text-muted-foreground"><Clock3 className="mx-auto mb-2 h-7 w-7" />{allRecords.length ? "No invitations match this filter." : "No speaker invitations yet."}</div>}</section>
      <section className="rounded-2xl border bg-card p-6 shadow-sm">{!selected ? <div className="py-10 text-center text-muted-foreground">Choose a speaker-event record to see its next actions and history.</div> : detail.isLoading ? <p>Loading details…</p> : <><h2 className="text-2xl">{selected.speaker_name}</h2><p className="mt-1 text-muted-foreground">{selected.event_title} · {labels[selected.status]}</p><div className="mt-5 flex flex-wrap gap-2">{actions.map(([status,label]) => <button key={status} disabled={transition.isPending} onClick={() => transition.mutate({ record: selected, status })} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60">{label}</button>)}</div>{!actions.length ? <p className="mt-5 rounded-xl bg-muted p-3 text-sm">No action is needed from your role at this stage.</p> : null}
        <form onSubmit={(event) => { event.preventDefault(); addNote.mutate(); }} className="mt-6 border-t pt-5"><h3 className="flex items-center gap-2 text-lg"><MessageSquareText className="h-4 w-4" />Internal notes</h3><div className="mt-3 flex gap-2"><input required value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add context for the other role" className="min-w-0 flex-1 rounded-xl border bg-input-background px-3 py-2" /><button disabled={addNote.isPending} className="rounded-xl border px-4 font-semibold">Add</button></div><div className="mt-4 space-y-2">{detail.data?.notes.map((item) => <div key={item.id} className="rounded-xl bg-muted p-3 text-sm"><p>{item.body}</p><time className="mt-1 block text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</time></div>)}</div></form>
        <div className="mt-6 border-t pt-5"><h3 className="text-lg">Status history</h3><ol className="mt-3 space-y-3">{detail.data?.history.map((item) => <li key={item.id} className="border-l-2 border-primary/30 pl-3 text-sm"><p className="font-medium">{labels[item.to_status]}</p><p className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}{item.correction_reason ? ` · Correction: ${item.correction_reason}` : ""}</p></li>)}</ol></div>
        {role === "connector" && !["event_cancelled","attended","did_not_attend"].includes(selected.status) ? <form onSubmit={(event) => { event.preventDefault(); correct.mutate(selected); }} className="mt-6 rounded-xl border border-[#CFBAB0] p-4"><h3 className="font-semibold">Correct an error</h3><p className="mt-1 text-xs text-muted-foreground">Corrections are recorded in the history and require a reason.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={correctionStatus} onChange={(e) => setCorrectionStatus(e.target.value as SpeakerEventStatus)} className="rounded-xl border bg-input-background px-3 py-2">{Object.entries(labels).filter(([key]) => !["attended","did_not_attend","event_cancelled"].includes(key)).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><input required value={correctionReason} onChange={(e) => setCorrectionReason(e.target.value)} placeholder="Reason for correction" className="rounded-xl border bg-input-background px-3 py-2" /></div><button disabled={correct.isPending} className="mt-3 min-h-11 rounded-xl border px-4 text-sm font-semibold">Save correction</button></form> : null}
        {(transition.error || addNote.error || correct.error) ? <p role="alert" className="mt-4 text-sm text-destructive">{(transition.error ?? addNote.error ?? correct.error) instanceof Error ? (transition.error ?? addNote.error ?? correct.error as Error).message : "The change could not be saved."}</p> : null}</>}</section></div>
  </div>;
}
