import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Plus, Upload } from "lucide-react";
import { usePrincipalKey } from "../components/PrincipalQueryProvider";
import { createSpeaker, fetchSpeakers, publishSpeakerRoster, updateSpeaker, type SpeakerProfile, type SpeakerProfileInput } from "../../lib/api";
import { useAuthorizedUnitId } from "../hooks/useAuthorizedUnit";

const blank: SpeakerProfileInput = { name: "", title: "", company: "", board_role: "", expertise_topics: [], home_region: "", service_regions: [], contact_email: "", contact_phone: "", available: true, active: true };
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export function Volunteers() {
  const unitId = useAuthorizedUnitId("admin"); const principalKey = usePrincipalKey(); const client = useQueryClient();
  const [selected, setSelected] = useState<SpeakerProfile | null>(null); const [form, setForm] = useState(blank); const [topics, setTopics] = useState(""); const [regions, setRegions] = useState("");
  const key = [principalKey, "speakers", unitId] as const;
  const query = useQuery({ queryKey: key, queryFn: () => fetchSpeakers(unitId!), enabled: Boolean(principalKey && unitId) });
  useEffect(() => { if (selected) { setForm({ name: selected.name, title: selected.title, company: selected.company, board_role: selected.board_role, expertise_topics: selected.expertise_topics, home_region: selected.home_region, service_regions: selected.service_regions, contact_email: selected.contact_email, contact_phone: selected.contact_phone, available: selected.available ?? true, active: selected.active ?? true }); setTopics(selected.expertise_topics.join(", ")); setRegions(selected.service_regions.join(", ")); } }, [selected]);
  const save = useMutation({ mutationFn: () => selected ? updateSpeaker(unitId!, selected.id, { ...form, expertise_topics: split(topics), service_regions: split(regions), version: selected.version! }) : createSpeaker(unitId!, { ...form, expertise_topics: split(topics), service_regions: split(regions) }), onSuccess: async () => { setSelected(null); setForm(blank); setTopics(""); setRegions(""); await client.invalidateQueries({ queryKey: key }); } });
  const publish = useMutation({ mutationFn: () => publishSpeakerRoster(unitId!), onSuccess: async () => client.invalidateQueries({ queryKey: key }) });
  if (!unitId) return <section className="rounded-2xl border bg-card p-8"><h1 className="text-3xl">Speakers</h1><p className="mt-2 text-muted-foreground">Sign in with an authorized unit to manage its speaker roster.</p></section>;
  const speakers = query.data?.data ?? [];
  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Speakers</h1><p className="mt-2 text-muted-foreground">Maintain private contact details, availability, and the roster Event Hosts can match.</p></div><button disabled={publish.isPending} onClick={() => publish.mutate()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-semibold text-primary-foreground disabled:opacity-60"><Upload className="h-4 w-4" />{publish.isPending ? "Publishing…" : "Publish roster"}</button></header>
    {query.data?.published_at ? <p className="rounded-xl bg-primary/5 p-3 text-sm text-primary"><CheckCircle2 className="mr-2 inline h-4 w-4" />Published roster version {query.data.roster_version} on {new Date(query.data.published_at).toLocaleString()}.</p> : <p className="rounded-xl bg-accent/15 p-3 text-sm">The roster has not been published. Event Hosts cannot run Smart Match yet.</p>}
    <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
      <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl">Roster</h2><button onClick={() => { setSelected(null); setForm(blank); setTopics(""); setRegions(""); }} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm font-semibold"><Plus className="h-4 w-4" />New speaker</button></div>{query.isLoading ? <p className="mt-4">Loading speakers…</p> : query.error ? <p role="alert" className="mt-4 text-destructive">{query.error instanceof Error ? query.error.message : "Speakers could not be loaded."}</p> : speakers.length ? <div className="mt-4 space-y-2">{speakers.map((speaker) => <button key={speaker.id} onClick={() => setSelected(speaker)} className={`w-full rounded-xl border p-4 text-left ${selected?.id === speaker.id ? "border-primary bg-primary/5" : "hover:bg-muted/50"}`}><div className="flex justify-between gap-3"><div><p className="font-semibold">{speaker.name}</p><p className="text-sm text-muted-foreground">{[speaker.title, speaker.company].filter(Boolean).join(" · ") || "Profile details not set"}</p></div><span className={`text-xs font-semibold ${speaker.available && speaker.active ? "text-primary" : "text-muted-foreground"}`}>{!speaker.active ? "Inactive" : speaker.available ? "Available" : "Unavailable"}</span></div><p className="mt-2 text-xs text-muted-foreground">{speaker.expertise_topics.join(", ") || "No topics yet"}</p></button>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No speakers yet. Add the first person to the roster.</p>}</section>
      <form onSubmit={(event) => { event.preventDefault(); save.mutate(); }} className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-2xl">{selected ? "Edit speaker" : "Add speaker"}</h2><p className="mt-1 text-sm text-muted-foreground">Contact details remain visible only to Speaker Connectors.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
        {([['name','Name'],['title','Title'],['company','Company'],['board_role','Board role'],['home_region','Home region'],['contact_email','Email'],['contact_phone','Phone']] as const).map(([name,label]) => <label key={name}>{label}<input required={name === "name"} type={name === "contact_email" ? "email" : "text"} value={(form[name] as string | null | undefined) ?? ""} onChange={(e) => setForm((current) => ({ ...current, [name]: e.target.value }))} className="mt-1 w-full rounded-xl border bg-input-background px-3 py-2" /></label>)}
        <label className="sm:col-span-2">Expertise topics <span className="text-xs text-muted-foreground">(comma separated)</span><input value={topics} onChange={(e) => setTopics(e.target.value)} className="mt-1 w-full rounded-xl border bg-input-background px-3 py-2" /></label><label className="sm:col-span-2">Service regions <span className="text-xs text-muted-foreground">(comma separated)</span><input value={regions} onChange={(e) => setRegions(e.target.value)} className="mt-1 w-full rounded-xl border bg-input-background px-3 py-2" /></label>
        <label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.available} onChange={(e) => setForm((current) => ({ ...current, available: e.target.checked }))} />Available for events</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.active} onChange={(e) => setForm((current) => ({ ...current, active: e.target.checked }))} />Active profile</label>
      </div>{save.error ? <p role="alert" className="mt-4 text-sm text-destructive">{save.error instanceof Error ? save.error.message : "The speaker could not be saved."}</p> : null}<button disabled={save.isPending} className="mt-5 min-h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground disabled:opacity-60">{save.isPending ? "Saving…" : "Save speaker"}</button></form>
    </div>
  </div>;
}
